=== IrynaZazyba/XmlParser/src/main/resources/xsd/tests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.jwd.epm.by/test"
        xmlns:tns="http://www.jwd.epm.by/test">

    <element name="tests">
        <complexType>
            <sequence>
                <element name="test" type="tns:Test" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Test">
        <sequence>
            <element name="title" type="string"/>
            <element name="key" type="int"/>
            <element name="time" type="time"/>
            <element name="deleted_at" type="date" minOccurs="0"/>
            <element name="test-group" type="tns:TestGroup"/>
            <element name="questions">
                <complexType>
                    <sequence>
                        <element name="question" type="tns:Question" minOccurs="10" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>

        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>


    <complexType name="Question">
        <sequence>
            <element name="question-text" type="string"/>
            <element name="answers">
                <complexType>
                    <sequence>
                        <element name="answer" type="tns:Answer" minOccurs="3" maxOccurs="4"/>
                    </sequence>
                </complexType>
            </element>
            <element name="deleted_at" type="date" minOccurs="0"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>


    <complexType name="Answer">
        <sequence>
            <element name="answer-text" type="string"/>
            <element name="result" type="boolean"/>
            <element name="deleted_at" type="date" minOccurs="0"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>

    <complexType name="TestGroup">
        <sequence>
            <element name="group-title" type="tns:TestGroupValue"/>
            <element name="deleted_at" type="date" minOccurs="0"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>

    <simpleType name="TestGroupValue">
        <restriction base="string">
            <maxLength value="15"/>
        </restriction>
    </simpleType>


</schema>

=== IrynaZazyba/XmlParser/src/main/resources/tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:tests xmlns:tc="http://www.jwd.epm.by/test"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.jwd.epm.by/test /xsd/tests.xsd">

    <test id="T-1">
        <title>Article</title>
        <key>5308</key>
        <time>00:35:00</time>
        <test-group id="1">
            <group-title>English</group-title>
        </test-group>
        <questions>
            <question id="Q-8">
                <question-text>Canada is one of ___ biggest countries in the world.</question-text>
                <answers>
                    <answer id="A-17">
                        <answer-text>a</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-18">
                        <answer-text>-</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-19">
                        <answer-text>the</answer-text>
                        <result>true</result>
                    </answer>
                    <answer id="A-20">
                        <answer-text>an</answer-text>
                        <result>false</result>
                    </answer>
                </answers>
            </question>
            <question id="Q-9">
                <question-text>I want to see ___ movie. I don't care which one we see. I just want to get out of the house tonight.
                </question-text>
                <answers>
                    <answer id="A-25">
                        <answer-text>an</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-26">
                        <answer-text>a</answer-text>
                        <result>true</result>
                    </answer>
                    <answer id="A-27">
                        <answer-text>-</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-28">
                        <answer-text>the</answer-text>
                        <result>false</result>
                    </answer>
                </answers>
            </question>
            <question id="Q-10">
                <question-text>Do you like ___ my new glasses?</question-text>
                <answers>
                    <answer id="A-21">
                        <answer-text>the</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-22">
                        <answer-text>a</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-23">
                        <answer-text>an</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-24">
                        <answer-text>-</answer-text>
                        <result>true</result>
                    </answer>
                </answers>
            </question>
            <question id="Q-11">
                <question-text>I'd like to introduce you to ___ my brother.</question-text>
                <answers>
                    <answer id="A-32">
                        <answer-text>a</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-33">
                        <answer-text>-</answer-text>
                        <result>true</result>
                    </answer>
                    <answer id="A-34">
                        <answer-text>the</answer-text>
                        <result>false</result>
                    </answer>
                </answers>
            </question>
            <question id="Q-2">
                <question-text>It's really hot here. We live close to ___ equator.</question-text>
                <answers>
                    <answer id="A-29">
                        <answer-text>the</answer-text>
                        <result>true</result>
                    </answer>
                    <answer id="A-30">
                        <answer-text>an</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-31">
                        <answer-text>-</answer-text>
                        <result>false</result>
                    </answer>
                </answers>
            </question>
            <question id="Q-13">
                <question-text>I am ___ teacher. My husband is an accountant.</question-text>
                <answers>
                    <answer id="A-38">
                        <answer-text>-</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-39">
                        <answer-text>an</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-40">
                        <answer-text>the</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-41">
                        <answer-text>a</answer-text>
                        <result>true</result>
                    </answer>
                </answers>
            </question>
            <question id="Q-14">
                <question-text>She is ___ tallest girl in the school.</question-text>
                <answers>
                    <answer id="A-42">
                        <answer-text>the</answer-text>
                        <result>true</result>
                    </answer>
                    <answer id="A-43">
                        <answer-text>an</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-44">
                        <answer-text>the</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-45">
                        <answer-text>a</answer-text>
                        <result>false</result>
                    </answer>
                </answers>
            </question>
            <question id="Q-3">
                <question-text>Where is ___ nearest gas station?</question-text>
                <answers>
                    <answer id="A-54">
                        <answer-text>a</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-55">
                        <answer-text>the</answer-text>
                        <result>true</result>
                    </answer>
                    <answer id="A-56">
                        <answer-text>-</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-57">
                        <answer-text>an</answer-text>
                        <result>false</result>
                    </answer>
                </answers>
            </question>
            <question id="Q-4">
                <question-text>What does he do for ___ living?</question-text>
                <answers>
                    <answer id="A-46">
                        <answer-text>the</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-47">
                        <answer-text>an</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-48">
                        <answer-text>-</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-49">
                        <answer-text>a</answer-text>
                        <result>true</result>
                    </answer>
                </answers>
            </question>
            <question id="Q-5">
                <question-text>Do you like playing ___ baseball?</question-text>
                <answers>
                    <answer id="A-50">
                        <answer-text>the</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-51">
                        <answer-text>an</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A-52">
                        <answer-text>-</answer-text>
                        <result>true</result>
                    </answer>
                    <answer id="A-53">
                        <answer-text>the</answer-text>
                        <result>false</result>
                    </answer>
                </answers>
            </question>
        </questions>
    </test>
    <test id="T-2">
        <title>Modal verb</title>
        <key>5308</key>
        <time>00:35:00</time>
        <test-group id="1">
            <group-title>English</group-title>
        </test-group>
        <questions>
            <question id="Q2-8">
                <question-text>I may ___ able to come to your party if I have the time.</question-text>
                <answers>
                    <answer id="A2-17">
                        <answer-text>be</answer-text>
                        <result>true</result>
                    </answer>
                    <answer id="A2-18">
                        <answer-text>can</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A2-19">
                        <answer-text>have to</answer-text>
                        <result>false</result>
                    </answer>
                    <answer id="A2-20">
                        <answer-text>should</answer-text>
